version: '3'
services:
  grafana:
    build: ./grafana/
    container_name: grafana
    ports:
      - 3000:3000
      - 3333:3333
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-mongodb-datasource
      - GF_SECURITY_ADMIN_USER=admin
    networks:
      - hadoop
    volumes:
      - './grafana/data:/var/lib/grafana'

  mongodb:
    image: mongo
    container_name: db_mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - './mongo_data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: roottoor
    networks:
      hadoop:
        ipv4_address: 172.50.0.21
        aliases:
          - internal.db.tn
  tcp_streamer:
    build: ./tcp_streamer/
    container_name: tcp_streamer
    networks:
      - hadoop
    ports:
      - 1337:1337
  
  kafka_streamer:
    build: ./kafka_streamer/
    container_name: kafka_streamer
    networks:
      - hadoop
    restart: always

  hadoop-master:
    build: ./master/
    container_name: hadoop-master
    hostname: hadoop-master
    # tty: true
    ports:
      - 9870:9870
      - 8088:8088
      - 7077:7077
      - 16010:16010
    networks:
      hadoop:

  hadoop-worker1:
    build: ./worker/
    container_name: hadoop-worker1
    hostname: hadoop-worker1
    # tty: true
    ports:
      - 8040:8042
    networks:
      hadoop:

  hadoop-worker2:
    build: ./worker/
    container_name: hadoop-worker2
    hostname: hadoop-worker2
    # tty: true
    ports:
      - 8041:8042
    networks:
      hadoop:

networks:
  hadoop:
    external: true
